//placeholder only
all:	mergesort insertsort
mergesort: mergesort.cpp
	g++ mergesort.cpp -o mergesort 

insertsort: insertsort.cpp
	g++ insertsort.cpp -o insertsort
clean:
	rm -f *.out *.o mergesort insertsort
